story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webs6.urls')),
]

webs6/urls.py
from django.urls import path
from . import views

app_name = 'webs6'

urlpatterns = [
    path('', views.Story6_home, name = 'home'),
    path('tambahKegiatan/', views.Story6_tambahKegiatan, name = "s6tk"),
    path('tambahPeserta/<int:id>', views.Story6_tambahPeserta, name = "s6tp"),
]

webs6/models.py
from django.db import models

# Create your models here.


class Peserta(models.Model):
    nama_peserta = models.TextField(max_length = 100, unique=True)
    def __str__(self):
        return self.nama_peserta

class Kegiatan(models.Model):
    nama_kegiatan = models.TextField(max_length = 100, unique=True)
    peserta = models.ManyToManyField(Peserta,blank=True)
    def __str__(self):
        return self.nama_kegiatan

webs6/forms.py
from django import forms
from django.forms import ModelForm
from .models import Peserta, Kegiatan

class FormTambahPeserta(forms.ModelForm):
    nama_peserta = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control w-40",
        "placeholder" : "Nama Peserta"
    }), label = "")

    class Meta:
        model = Peserta
        fields = "__all__"

class FormTambahKegiatan(forms.ModelForm):
    nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs = {"class":"form-control w-50 text-center",
        "placeholder" : "Nama Kegiatan"
    }), label = "")

    class Meta:
        model = Kegiatan
        fields = "__all__"

webs6/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, reverse
from .forms import FormTambahPeserta, FormTambahKegiatan
from .models import Kegiatan, Peserta
from django.contrib import messages

# Create your views here.

def Story6_home(request):
    context = {
        "activities" : Kegiatan.objects.all(),
        "formPeserta" : FormTambahPeserta,
    }
    return render(request, 'Story6_home.html', context)

def Story6_tambahPeserta(request, id):
    if request.method == "POST":
        kegiatan = Kegiatan.objects.get(id=id)
        nama_baru = request.POST["nama_peserta"]

        peserta_baru, status_baru = Peserta.objects.get_or_create(nama_peserta = nama_baru)
        if status_baru:
            peserta_baru.save()
            kegiatan.peserta.add(peserta_baru)
            messages.add_message(request, messages.SUCCESS, "{} berhasil ditambahkan ke {}".format(nama_baru, kegiatan.nama_kegiatan))
        else:
            try:
                kegiatan.peserta.get(nama_peserta=nama_baru)
                messages.add_message(request, messages.WARNING, "{} sudah di kegiatan {}".format(nama_baru, kegiatan.nama_kegiatan))
            except:
                kegiatan.peserta.add(peserta_baru)
                messages.add_message(request, messages.SUCCESS, "{} berhasil ditambahkan ke {}".format(nama_baru, kegiatan.nama_kegiatan))
    return redirect(reverse("webs6:home"))

def Story6_tambahKegiatan(request):
    if request.method == "POST":
        keg_form = FormTambahKegiatan(request.POST)
        if keg_form.is_valid():
            keg_obj = keg_form.save(commit=False)
            keg_form.save()
        return redirect(reverse("webs6:home"))
    context = {
        "keg_form" : FormTambahKegiatan,
        "is_tambah_kegiatan" : True
    }
    return render(request, "Story6_tambahKegiatan.html", context)

webs6/templates/Story6_base.html
{% load static %}
<html lang=en>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>

    <body style="background-color: gold;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Story 6</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webs6:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'webs6:s6tk' %}">Tambah Kegiatan</a>
              </div>
            </div>
        </nav>

        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show mx-2" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
        {% endfor %}
      {% endif %}
     
        {% block content %}
        {% endblock %}
    </body>
</html>

webs6/templates/Story6_home.html
{% extends 'Story6_base.html' %}
{% load static %}

{% block content %}
<div class= "container">
    <h2>Daftar Kegiatan</h2>
    {% for kegiatan in activities %}
        <h5>Nama Kegiatan:</h5>
        <h5>{{kegiatan.nama_kegiatan}}</h5>
        <div class = "container">
            <h5>Peserta:</h5>
            <form>
                {% csrf_token %}
                {% for peserta in kegiatan.peserta.all %}
                <h4>{{peserta.nama_peserta}}</h4>
                {% endfor %}
            </form>
            <form action="{% url 'webs6:s6tp' id=kegiatan.id %}" method = "POST">
                {% csrf_token %}
                {{formPeserta}}
                <input class="btn btn-primary ml-1" type="submit" value="Tambah Peserta"> 
            </form>
        </div>
    {% endfor %}
</div>
{% endblock %}

webs6/templates/Story6_tambahKegiatan.html
{% extends 'Story6_base.html' %}
{% load static %}

{% block content %}
<div>
    <form class="mt-5 d-flex justify-content-center align-items-center flex-column" action="{% url 'webs6:s6tk' %}" method="POST">
        <h3>Tambahkan kegiatan yang diinginkan</h3>
        {% csrf_token %}
        {{keg_form}}
        <input class="btn btn-secondary mt-2" type="submit" value="tambah kegiatan">
    </form>
</div>
{% endblock content %}